---
latest_release_filename: "/Users/pivotal/go/src/github.com/cloudfoundry-incubator/bosh-windows-acceptance-tests/assets/errand-release/dev_releases/errand-release/errand-release-0+dev.1469564930.yml"
